# Generated by Django 4.1.3 on 2022-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_university_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='student',
            name='allocated_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_students', to='main.sponsor'),
        ),
    ]
