# Generated by Django 4.1.3 on 2022-11-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sponsor_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='SponsorRequest',
        ),
    ]
