# Generated by Django 4.1.3 on 2022-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dashboard_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsors_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='amount_due',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='amount_paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='amount_requested',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sponsors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
