# Generated by Django 4.1.3 on 2022-11-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sponsordailystat_studentdailystat_delete_stat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsordailystat',
            old_name='sponsors_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='studentdailystat',
            old_name='students_count',
            new_name='count',
        ),
    ]
